import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";

const sourGummy = localFont({
    src: "./fonts/SourGummy-Regular.ttf",
    display: "swap",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${sourGummy.className} antialiased`}
            >
                <Navbar />
                {children}
            </body>
        </html>
    );
}
